env:
  browser: true
  commonjs: true
  es6: true
  node: true
  jest: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion : 2017
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - import
settings:
  import/resolver:
    babel-module: {}
rules:
  react/jsx-uses-react: 2
  react/jsx-uses-vars : 2
  import/imports-first: 2
  import/no-unresolved: 2
  import/default: 2
  import/named: 2
  import/no-named-as-default-member: 2
  import/no-mutable-exports: 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
